---
# Handlers for the hardening role

- name: Restart sshd
  ansible.builtin.service:
    name: ssh
    state: restarted

- name: Restart auditd
  ansible.builtin.service:
    name: auditd
    state: restarted
